/*
 * ui_views.h
 *
 *  Created on: 18 feb. 2026
 *      Author: oscar
 */

#pragma once
#include "ui_view_mgr.h"

/* Vistas disponibles (definidas en view_registro.c / view_registro_opts.c) */
extern const UiView VIEW_PRODUCTO;
extern const UiView VIEW_USUARIO;

extern const UiView VIEW_APRENDER;
extern const UiView VIEW_APRENDER_FAST;
extern const UiView VIEW_APRENDER_RESULTS;

extern const UiView VIEW_REGISTRO;
extern const UiView VIEW_REGISTRO_OPTS;

extern const UiView VIEW_OPCIONES;
extern const UiView VIEW_OPCIONES_PRODUCTO;
extern const UiView VIEW_OPCIONES_SISTEMA;

extern const UiView VIEW_OPCIONES_PRODUCTO_ADMIN;
extern const UiView VIEW_CFG_PROD_ADMIN_CAMBIO;
extern const UiView VIEW_CFG_PROD_ADMIN_CREAR;
extern const UiView VIEW_CFG_PROD_ADMIN_ELIMINAR;

extern const UiView VIEW_OPCIONES_PRODUCTO_DATOSP;

extern const UiView VIEW_OPCIONES_PRODUCTO_APRENDER;
extern const UiView VIEW_CFG_PROD_APRENDER_APRAPIDO;
extern const UiView VIEW_CFG_PROD_APRENDER_APRESULTADOS;

extern const UiView VIEW_OPCIONES_PRODUCTO_AUDITORIA;
extern const UiView VIEW_OPCIONES_PRODUCTO_AUDITORIA_AJUSTES;
extern const UiView VIEW_OPCIONES_PRODUCTO_AUDITORIA_PROBETAS;
extern const UiView VIEW_OPCIONES_PRODUCTO_AUDITORIA_TPRODUCTOS;
extern const UiView VIEW_OPCIONES_PRODUCTO_AUDITORIA_INIMANUAL;

extern const UiView VIEW_OPCIONES_PRODUCTO_SALIDAS;
extern const UiView VIEW_OPCIONES_PRODUCTO_SALIDAS_AJUSTES;
extern const UiView VIEW_OPCIONES_PRODUCTO_SALIDAS_TPRODUCTOS;
extern const UiView VIEW_OPCIONES_PRODUCTO_SALIDAS_MOMR;

extern const UiView VIEW_OPCIONES_PRODUCTO_AJUSTES;

extern const UiView VIEW_OPCIONES_SISTEMA_ADMUSERS;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_EDITAR;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_CREAR;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_ELIMINAR;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_COPIAR;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_AJUSTES;
extern const UiView VIEW_OPCIONES_SISTEMA_ADMINUSERS_LOGIN2GO;

extern const UiView VIEW_OPCIONES_SISTEMA_SHARDWARE;
extern const UiView VIEW_OPCIONES_SISTEMA_SHARDWARE_ES;
extern const UiView VIEW_OPCIONES_SISTEMA_SHARDWARE_UC;
extern const UiView VIEW_OPCIONES_SISTEMA_SHARDWARE_VERSIONES;
extern const UiView VIEW_OPCIONES_SISTEMA_SHARDWARE_DEPURAR;

extern const UiView VIEW_OPCIONES_SISTEMA_ESTADISTICAS;
extern const UiView VIEW_OPCIONES_SISTEMA_ESTADISTICAS_CONT;
extern const UiView VIEW_OPCIONES_SISTEMA_ESTADISTICAS_MSIGNAL;
extern const UiView VIEW_OPCIONES_SISTEMA_ESTADISTICAS_GRAF;
extern const UiView VIEW_OPCIONES_SISTEMA_ESTADISTICAS_AJUSTES;

extern const UiView VIEW_OPCIONES_SISTEMA_AUDITORIA;

extern const UiView VIEW_OPCIONES_SISTEMA_CONFFABRICA;
extern const UiView VIEW_OPCIONES_SISTEMA_CONFABRICA_GCONFIG;
extern const UiView VIEW_OPCIONES_SISTEMA_CONFABRICA_RCONFIG;

extern const UiView VIEW_OPCIONES_SISTEMA_LICENCIA;
extern const UiView VIEW_OPCIONES_SISTEMA_LICENCIA_CARACTERISTICAS;
extern const UiView VIEW_OPCIONES_SISTEMA_LICENCIA_EXPORTAR;
extern const UiView VIEW_OPCIONES_SISTEMA_LICENCIA_IMPORTAR;
extern const UiView VIEW_OPCIONES_SISTEMA_LICENCIA_REESTABLECER;

extern const UiView VIEW_OPCIONES_PERIFERICOS;
extern const UiView VIEW_OPCIONES_PERIFERICOS_OPCEXP;
extern const UiView VIEW_OPCIONES_PERIFERICOS_SUPERV;
extern const UiView VIEW_OPCIONES_PERIFERICOS_SUP_RECHAZO;
extern const UiView VIEW_OPCIONES_PERIFERICOS_SUP_SENAIRE;
extern const UiView VIEW_OPCIONES_PERIFERICOS_SUP_CONTLLENO;

extern const UiView VIEW_OPCIONES_PERIFERICOS_ADVERTENCIA;

extern const UiView VIEW_OPCIONES_PERIFERICOS_AUTOTEST;

extern const UiView VIEW_OPCIONES_ENTRADAS;
extern const UiView VIEW_OPCIONES_ENTRADAS_EXTERNO;
extern const UiView VIEW_OPCIONES_ENTRADAS_DIGITAL;
extern const UiView VIEW_OPCIONES_ENTRADAS_CONFIGURABLE;
extern const UiView VIEW_OPCIONES_ENTRADAS_CONFIG_AJUST;
extern const UiView VIEW_OPCIONES_ENTRADAS_CONFIG_ENT1;
extern const UiView VIEW_OPCIONES_ENTRADAS_CONFIG_ENT2;
extern const UiView VIEW_OPCIONES_ENTRADAS_CONFIG_ENT3;

extern const UiView VIEW_OPCIONES_BOBINA;
extern const UiView VIEW_OPCIONES_BOBINA_AJUSTES;
extern const UiView VIEW_OPCIONES_BOBINA_DFREC;

extern const UiView VIEW_OPCIONES_USB;
extern const UiView VIEW_OPCIONES_USB_EXPREG;
extern const UiView VIEW_OPCIONES_USB_EXPORTAR;
extern const UiView VIEW_OPCIONES_USB_IMPORTAR;
extern const UiView VIEW_OPCIONES_USB_LOGIN2GO;

extern const UiView VIEW_REGISTRO_AJREG;
extern const UiView VIEW_REGISTRO_FREG;
extern const UiView VIEW_REGISTRO_BREG;
extern const UiView VIEW_REGISTRO_EXPREG;

extern const UiView VIEW_OPCIONES_PRODUCTO_MSPEED;
extern const UiView VIEW_OPCIONES_PRODUCTO_MSPEED_INFO;
extern const UiView VIEW_OPCIONES_PRODUCTO_MSPEED_MEDIC;
extern const UiView VIEW_OPCIONES_PRODUCTO_MSPEED_CALCULA;
extern const UiView VIEW_OPCIONES_PRODUCTO_MSPEED_AJUSTES;

extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES;
extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES_RED;
extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES_CLAN;
extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES_CONEX;
extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES_ESSERIE;
extern const UiView VIEW_OPCIONES_SISTEMA_INTERFACES_SERVIDOR;

extern const UiView VIEW_OPCIONES_SISTEMA_CONFIG;

extern const UiView VIEW_REGISTRO_FILTREG;
extern const UiView VIEW_REGISTRO_FECHAHORA;
