/*
 * ui_view_ids.h
 *
 *  Created on: 18 feb. 2026
 *      Author: oscar
 */


#pragma once
#include <stdint.h>

typedef enum
{
	// --- APRENDER submenu (View) ---
	UI_VID_APR_FAST     	 				= 40,  // Aprend. rapido
	UI_VID_APR_RESULTS   					= 41,  // Resultados
	UI_VID_APR_BACK     	 				= 42,  // X (cerrar)
	// --- APRENDER views secundarios ---
	UI_VID_APRF_BACK     					= 43,   // X en "Aprend. rapido"
	UI_VID_APRR_BACK     					= 44,   // X en "Resultados"

    // ---- REGISTRO (100..199) ----
    UI_VID_REG_BACK      					= 100, // CRUZ ROJA (pop)
    UI_VID_REG_CONFIG    					= 101, // CONFIG (push opciones)
    UI_VID_REG_UP        					= 102, // Flecha arriba (scroll -)
    UI_VID_REG_DOWN      					= 103, // Flecha abajo (scroll +)

    // ---- OPCIONES DE REGISTRO (200..299) ----
    UI_VID_ROPT_BACK     					= 200, // CRUZ ROJA (pop)
    UI_VID_ROPT_BTN0     					= 201, // botones de opciones (ejemplos)
    UI_VID_ROPT_BTN1     					= 202,
    UI_VID_ROPT_BTN2     					= 203,
    UI_VID_ROPT_BTN3     					= 204,

	 // ---- OPCIONES (CONFIG) (300..399) ----
	 UI_VID_OPT_BACK       					= 60, // CRUZ ROJA (pop)
	 UI_VID_OPT_PRODUCTO   					= 61,
	 UI_VID_OPT_SISTEMA    					= 62,
	 UI_VID_OPT_PERIF      					= 63,
	 UI_VID_OPT_ENTRADAS   					= 64,
	 UI_VID_OPT_BOBINA     					= 65,
	 UI_VID_OPT_USB        					= 66,

	 // CONFIGURACION - OPCIONES - PRODUCTO
	 UI_VID_OPT_PROD_BACK       			= 67, // CRUZ ROJA (pop)
     UI_VID_OPT_PROD_ADM   					= 68,
	 UI_VID_OPT_PROD_DATOS    				= 69,
	 UI_VID_OPT_PROD_APRENDER      			= 70,
	 UI_VID_OPT_PROD_AUDITORIA   			= 71,
	 UI_VID_OPT_PROD_SALIDAS     			= 72,
	 UI_VID_OPT_PROD_AJUSTES        		= 73,

	 // CONFIGURACION - OPCIONES - PRODUCTO - ADM PRODUCTOS
	 UI_VID_OPT_PROD_ADM_BACK       		= 74, // CRUZ ROJA (pop)
	 UI_VID_OPT_PROD_ADM_CAMBIO   			= 75,
	 UI_VID_OPT_PROD_ADM_CREAR    			= 76,
	 UI_VID_OPT_PROD_ADM_ELIMINAR      		= 77,

	 // CONFIGURACION - OPCIONES - PRODUCTO - ADM PRODUCTOS - HOJAS
	 UI_VID_OPT_PROD_LEAF_BACK 				= 78, // X (pop) para hojas

	 // CONFIGURACION - OPCIONES - PRODUCTO - APRENDER - HOJAS
	 UI_VID_OPT_PROD_APRENDER_APRAPIDO 		= 79, // X (pop) para hojas
	 UI_VID_OPT_PROD_APRENDER_APRESULTADOS 	= 80,

	 // CONFIGURACION - OPCIONES - PRODUCTO - AUDITORIA
	 UI_VID_OPT_PROD_AUDITORIA_AJUSTES 		= 81, // X (pop) para hojas
	 UI_VID_OPT_PROD_AUDITORIA_PATRONES 	= 82,
	 UI_VID_OPT_PROD_AUDITORIA_TPRODUCTOS 	= 83, // X (pop) para hojas
	 UI_VID_OPT_PROD_AUDITORIA_INIMANUAL 	= 84,

	 // CONFIGURACION - OPCIONES - PRODUCTO - SALIDAS
     UI_VID_OPT_PROD_SALIDAS_AJUSTES 		= 85, // X (pop) para hojas
	 UI_VID_OPT_PROD_SALIDS_TPRODUCTOS 		= 86,
	 UI_VID_OPT_PROD_SALIDAS_MOMR 			= 87, // X (pop) para hojas

	 UI_VID_OPT_SIS_ADMUSERS				= 88,
	 UI_VID_OPT_SIS_SHARDW                  = 89,
	 UI_VID_OPT_SIS_ESTADIST				= 90,
	 UI_VID_OPT_SIS_INTERFACES				= 91,
	 UI_VID_OPT_SIS_AUDITORIA				= 92,
	 UI_VID_OPT_SIS_CONFFABRICA				= 93,
	 UI_VID_OPT_SIS_LICENCIA				= 94,

	 UI_VID_OPT_SIS_ADMUSERS_EDITAR         = 95,
	 UI_VID_OPT_SIS_ADMUSERS_CREAR          = 96,
	 UI_VID_OPT_SIS_ADMUSERS_ELIMINAR       = 97,
	 UI_VID_OPT_SIS_ADMUSERS_COPIAR         = 98,
	 UI_VID_OPT_SIS_ADMUSERS_AJUSTES        = 99,
	 UI_VID_OPT_SIS_ADMUSERS_LOGIN2GO       = 100,

	 UI_VID_OPT_SIS_SHARDWARE_ES            = 101,
	 UI_VID_OPT_SIS_SHARDWARE_UC            = 102,
	 UI_VID_OPT_SIS_SHARDWARE_VERSIONES     = 103,
	 UI_VID_OPT_SIS_SHARDWARE_DEPURAR       = 104,

	 UI_VID_OPT_SIS_ESTADISTICAS_CONT       = 105,
	 UI_VID_OPT_SIS_ESTADISTICAS_SMETAL     = 106,
	 UI_VID_OPT_SIS_ESTADISTICAS_GRAFICAS   = 107,
	 UI_VID_OPT_SIS_ESTADISTICAS_AJUSTES    = 108,

	 UI_VID_OPT_SIS_CONFABRICA_GUARDARC     = 109,
	 UI_VID_OPT_SIS_CONFABRICA_RESTAURARC   = 110,

	 UI_VID_OPT_SIS_LICENCIA_CARAC          = 111,
	 UI_VID_OPT_SIS_LICENCIA_EXPORTARINF    = 112,
	 UI_VID_OPT_SIS_LICENCIA_IMPORTAR       = 113,
	 UI_VID_OPT_SIS_LICENCIA_REESTABLECER   = 114,

	 UI_VID_OPT_PER_OPCEXP					= 115,
	 UI_VID_OPT_PER_SUPERV					= 116,
	 UI_VID_OPT_PER_ADVERT					= 117,
	 UI_VID_OPT_PER_PRAUTO					= 118,

	 UI_VID_OPT_SUP_RECHAZO					= 119,
	 UI_VID_OPT_SUP_SENSAIRE				= 120,
	 UI_VID_OPT_SUP_CONTLLENO				= 121,

	 UI_VID_OPT_ENTRADAS_EXT				= 122,
	 UI_VID_OPT_ENTRADAS_DIGITAL			= 123,
	 UI_VID_OPT_ENTRADAS_CONFIG				= 124,

	 UI_VID_OPT_ENTRADAS_CONFIG_AJUST		= 125,
	 UI_VID_OPT_ENTRADAS_CONFIG_ENT1		= 126,
	 UI_VID_OPT_ENTRADAS_CONFIG_ENT2		= 127,
	 UI_VID_OPT_ENTRADAS_CONFIG_ENT3		= 128,

	 UI_VID_OPT_BOBINA_AJUSTES				= 129,
	 UI_VID_OPT_BOBINA_DFREC				= 130,

	 UI_VID_SC3_AUDITORIA					= 131,

	 UI_VID_SC4_EXPMANUAL					= 132,
	 UI_VID_SC4_RECHAZO						= 133,

	 UI_VID_OPT_USB_EXPREG					= 134,
	 UI_VID_OPT_USB_EXP						= 135,
	 UI_VID_OPT_USB_IMPORT					= 136,
	 UI_VID_OPT_USB_LOGIN2GO				= 137,


} UiViewId;
